# Generated by Django 3.0.3 on 2020-09-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('list', models.TextField()),
                ('description', models.TextField()),
                ('pages', models.CharField(max_length=10)),
                ('img_url', models.TextField()),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
