# Generated by Django 3.0.3 on 2020-09-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
