# Generated by Django 3.0.3 on 2020-09-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_book', '0002_auto_20200901_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
