# Generated by Django 3.0.3 on 2020-09-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_book', '0004_auto_20200905_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_book.Book', unique=True)),
                ('rank', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'BestSeller',
            },
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
