# Generated by Django 3.0.3 on 2020-09-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_book', '0006_auto_20200913_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='list',
        ),
    ]
