# Generated by Django 3.0.3 on 2020-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_book', '0008_auto_20200914_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
