# Generated by Django 3.0.3 on 2020-09-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0001_initial'),
        ('api_book', '0004_auto_20200905_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.PROTECT, to='api_book.Book')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='api_user.AppUser')),
            ],
            options={
                'db_table': 'Bookshelf',
            },
        ),
    ]
