# Generated by Django 3.0.3 on 2020-09-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
