# Generated by Django 3.0.3 on 2020-09-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookshelf', '0002_auto_20200908_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
